name: ci

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm ci
      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
      - name: Build API Doc
        run: npm run doc
